language: php
php:
  - "5.2"
  - "5.3"
  - "5.4"

env: TMPDIR=/tmp

before_install:
 - phpenv rehash
 - sh ./tests/install_dependencies.sh
 - phpenv rehash

script:
 - cd tests/
 - php runalltests.php
